/**
 * A drift guard for `src/lib/api-schema.d.ts`.
 *
 * The file is generated from `openapi/mi-casa.yaml` by the root `gen:client`
 * script and committed, so a spec change that nobody regenerates would leave
 * the typed client silently describing routes the server no longer serves.
 *
 * Regenerating here is not an option: openapi-typescript pins `typescript@^5`
 * and this workspace pins 7, so it is run through `bunx --package` (network,
 * bun) rather than installed — neither of which belongs in a unit test. So
 * the guard is a checksum of the input plus a structural cross-check of the
 * output, which between them catch every realistic way the two drift:
 *
 *  - the spec changed at all (checksum), which is when a regeneration is due
 *  - a route was added, removed or renamed (paths), the change most likely to
 *    be missed by eye
 *
 * When this fails: run `npm run gen:client` from the repo root, commit the
 * regenerated file, and paste the new checksum below.
 */
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

const specPath = new URL("../../../openapi/mi-casa.yaml", import.meta.url);
const schemaPath = new URL("../src/lib/api-schema.d.ts", import.meta.url);

const SPEC_SHA256 =
  "2ca1da80b3624ce0970103c7caf65aab1ae29d466454791f5a74fee371c1e4c0";

const spec = readFileSync(specPath, "utf8");
const schema = readFileSync(schemaPath, "utf8");

/** Top-level `paths` keys: the two-space-indented `/…:` lines in the spec. */
function specPaths(): string[] {
  const body = spec.slice(
    spec.indexOf("\npaths:"),
    spec.indexOf("\ncomponents:"),
  );
  return [...body.matchAll(/^ {2}(\/\S*):$/gm)].map((match) => match[1]).sort();
}

/** The keys of the generated `paths` interface. */
function schemaPaths(): string[] {
  const body = schema.slice(
    schema.indexOf("export interface paths {"),
    schema.indexOf("export type webhooks"),
  );
  return [...body.matchAll(/^ {4}"(\/[^"]*)": \{$/gm)]
    .map((match) => match[1])
    .sort();
}

describe("api-schema.d.ts", () => {
  it("was generated from this exact spec", () => {
    const actual = createHash("sha256").update(spec).digest("hex");
    expect(
      actual,
      "openapi/mi-casa.yaml changed: run `npm run gen:client` at the repo root, commit apps/frontend/src/lib/api-schema.d.ts, and update SPEC_SHA256 in this test",
    ).toBe(SPEC_SHA256);
  });

  it("describes exactly the routes the spec declares", () => {
    expect(schemaPaths()).toEqual(specPaths());
  });

  it("is the generated file, not a hand-edited one", () => {
    expect(schema).toContain("auto-generated by openapi-typescript");
  });
});
